# fly.toml app configuration file generated for arekkutienda-api on 2023-10-15T21:34:18-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "arekkutienda-api"
primary_region = "qro"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
